---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
  - name: Install Apache WebServer On CentOS
    ansible.builtin.yum:
      name: httpd
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: Install Apache WebServer On Ubuntu
    ansible.builtin.apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] == "Debian"
